
# This file was *autogenerated* from the file ./src/sage/rsa_func.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000); _sage_const_255 = Integer(255)
def rsaencrypt(Message, encrexp, encrmod):
    A = ASCIIPad(Message);
    E = power_mod(A,encrexp,encrmod);
    return(E);

def rsadecrypt(encr,decrexp,encrmod):
    D = power_mod(encr,decrexp,encrmod);
    N = ASCIIDepad(D);
    return(N);

########################################################################################
# The ASCIIPad takes a string (plaintext) as an input and gives a number as an output. #
# The number is represented in a ASCII like format that is padded.                     #
########################################################################################
def ASCIIPad(Message):
    K = (map(ord,reversed(Message)));    
    le= len(K);
    x = [_sage_const_100 +K[i] for i in range(le)];
    x = ZZ(x,_sage_const_1000 );
    return(x);
#################################################################################################
# The input is a number and the output is the original message. If the input is not padded ASCII#
# version of a message it returns the value: "This is not a padded ASCII string"                #
#################################################################################################
def ASCIIDepad(Number):
    n = Number.ndigits() % _sage_const_3 ;
    if (n > _sage_const_0 ):
        print("This is not a padded ASCII string\n");
    else:
        L = [((Number - (Number % (_sage_const_1000 **i)))/_sage_const_1000 **i)%_sage_const_1000  - _sage_const_100  for i in range(Number.ndigits()/_sage_const_3 )];
        N = "";
        for i in range(Number.ndigits()/_sage_const_3 ):
            N = chr(L[i]) + N;
        return(N)

def isASCIIPadded(Number):
    N = ""
    n = Number.ndigits() % _sage_const_3 ;
    if (n > _sage_const_0 ):
        return False;
    L = [((Number - (Number % (_sage_const_1000 **i)))/_sage_const_1000 **i)%_sage_const_1000  - _sage_const_100  for i in range(Number.ndigits()/_sage_const_3 )];
    for i in range(Number.ndigits()/_sage_const_3 ):
        if L[i] < _sage_const_0 :
            return False
        if L[i] > _sage_const_255 :
            return False
    return True

